<GP> ::= <distance> <inicializacao> <comando>
<inicializacao> ::= "random" <k> | "uniform" <k>
<comando> ::= <movimento> | (<movimento> <comando>)
<movimento> ::= "join" | "split" | "move1" | "move2" 
<k> ::= "4" | "6" | "8" | "10" | "0"
<distance> ::= "eucledian" | "manhatan"